travis:
  secure:
    BINSTAR_TOKEN: M4bYsuY52UJYtZvdoSfZqwtq9csAOQLMdNSd/6bS8uGE5EFI4Tj6UyiZ0vxSuusiWldNOLmXSLkYcptM82K86tH4lS6envNJa2OUfSYiuW4ZiFFxICiSHKIKH1I7LBtTVxa8IM8k3T4FYYfHlczSaaf2bVrI8ttEZfz+v6LElyBR71vK3MOCaw+2fvJLJvXMVoJUrf9X+2YxHTDx6fLQaZZbz9DNNQHEwO8DabL6lgynQd/tnZRWNeg90Vw5MYvLeByG29N3ADsxWas6QVR/cJZpOkuJmyHqQ68qkaVA7QlP8OJxC0tUku5l8p+ULF4nx8KhlS/3rulf1aGo9/pzXCaTaCYzfSjF9PbuV1REZu91oJRQyXe9hDmyHD33o9kY09/qjdsMV4bhy139PR+weRZBF4tfZLyZB+dF5OrfZ6ILPHtgyscliHzf5oCQlkI2+Jx4hdtR1caVR1IH3OMFL4+rU3wp1gl3ol3JiFufCNTLqN8NKZJFJSLwBWecsdMUSaBVdeq8XGVTaDNUlXn0e0gH0uZDnyT6lnBvNGoyZpnhAY+URC/o/1WoG7UBMcaH3/FFsI5uMhh0gtumRg4jXIeUgM9NQxwwtN+gOZD1q0ST1ptWtUqIwkNJpen2ZLylSyvbGwB6Mla/km304XZlKRicC7gO43Guhv/CzDH95wM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
